name: Test

on:
  push:
    branches:
      - 'main'

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 'main'

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          sudo ln -s /home/runner/.deno/bin/deno /usr/local/bin

      - name: Install and prepare Neovim
        run: |
          wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
          tar -zxf nvim-linux64.tar.gz
          sudo ln -s $(pwd)/nvim-linux64/bin/nvim /usr/local/bin

      - name: Run Tests
        run: ./scripts/run_tests.sh
